/* #region Etapa 1: Migración db_Hotel - Compatibilidad Oracle */

CREATE TABLE tbl_Empleados (
    CodigoEmpleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    NumeroDpi NUMBER(19) NOT NULL,
    Genero CHAR(1) NOT NULL,
    Cargo VARCHAR2(50) NOT NULL,
    Salario NUMBER(10, 2) NOT NULL,
    FechaNacimiento TIMESTAMP NOT NULL,
    FechaContratacion TIMESTAMP NOT NULL,
    Estado NUMBER(1) NOT NULL, -- 1: Activo, 0: Inactivo
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP
);

CREATE TABLE tbl_Usuarios (
    CodigoUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoEmpleado NUMBER NOT NULL,
    Correo VARCHAR2(100) NOT NULL,
    Usuario VARCHAR2(100) NOT NULL,
    Contrasenia VARCHAR2(100) NOT NULL,
    Rol VARCHAR2(100) NOT NULL,
    IntentosFallidos NUMBER,
    UltimoAcceso TIMESTAMP,
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_usu_emp FOREIGN KEY (CodigoEmpleado) REFERENCES tbl_Empleados(CodigoEmpleado)
);

CREATE TABLE tbl_PlanillasEnc (
    CodigoPlanillaEnc NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FechaPlanilla TIMESTAMP NOT NULL,
    TipoPlanilla VARCHAR2(50) NOT NULL,
    Banco VARCHAR2(50),
    DocReferencia NUMBER(19),
    TipoMoneda CHAR(3) NOT NULL,
    MontoTotal NUMBER(10,2) NOT NULL,
    Observaciones VARCHAR2(255),
    Estado VARCHAR2(50) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP
);

CREATE TABLE tbl_PlanillasDet (
    CodigoPlanillaDet NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoPlanillaEnc NUMBER NOT NULL,
    CodigoEmpleado NUMBER NOT NULL,
    SalarioBase NUMBER(10, 2) NOT NULL,
    BonoLey NUMBER(10,2) NOT NULL,
    BonoExtra NUMBER(10,2),
    HorasExtras NUMBER,
    MontoHorasExtras NUMBER(10,2),
    Isr NUMBER(10,2),
    Igss NUMBER(10,2),
    MontoTotal NUMBER(10, 2) NOT NULL,
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_det_enc FOREIGN KEY (CodigoPlanillaEnc) REFERENCES tbl_PlanillasEnc(CodigoPlanillaEnc),
    CONSTRAINT fk_det_emp FOREIGN KEY (CodigoEmpleado) REFERENCES tbl_Empleados(CodigoEmpleado)
);

CREATE TABLE tbl_Habitaciones (
    CodigoHabitacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Numero VARCHAR2(10) NOT NULL,
    Ubicacion VARCHAR2(100),
    Tipo VARCHAR2(50) NOT NULL,
    PetFriendly NUMBER(1),
    CantidadHuesped NUMBER,
    Precio NUMBER(10, 2) NOT NULL,
    PorcentajeAnticipo NUMBER(10,2),
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP
);

CREATE TABLE tbl_ServiciosHabitacion (
    CodigoServicioHab NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoEmpleado NUMBER NOT NULL,
    CodigoHabitacion NUMBER NOT NULL,
    TipoServicio VARCHAR2(50) NOT NULL,
    Turno CHAR(1) NOT NULL,
    FechaInicio TIMESTAMP NOT NULL,
    FechaFin TIMESTAMP NOT NULL,
    Observaciones VARCHAR2(255),
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_serv_emp FOREIGN KEY (CodigoEmpleado) REFERENCES tbl_Empleados(CodigoEmpleado),
    CONSTRAINT fk_serv_hab FOREIGN KEY (CodigoHabitacion) REFERENCES tbl_Habitaciones(CodigoHabitacion)
);

CREATE TABLE tbl_Huespedes (
    CodigoHuesped NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    TipoIdentificacion VARCHAR2(50) NOT NULL,
    NumeroIdentificacion NUMBER(19) NOT NULL,
    FechaNacimiento TIMESTAMP NOT NULL,
    Genero CHAR(1) NOT NULL,
    Telefono NUMBER,
    Direccion VARCHAR2(255),
    Calificacion NUMBER(10,2),
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP
);

CREATE TABLE tbl_Hospedajes (
    CodigoHospedaje NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoHuesped NUMBER NOT NULL,
    CodigoHabitacion NUMBER NOT NULL,
    FechaIngreso TIMESTAMP NOT NULL,
    FechaSalida TIMESTAMP NOT NULL,
    MontoHabitacion NUMBER(10,2),
    MontoAnticipo NUMBER(10,2),
    MontoConsumos NUMBER(10,2),
    MontoTotal NUMBER(10, 2) NOT NULL,
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_hosp_hue FOREIGN KEY (CodigoHuesped) REFERENCES tbl_Huespedes(CodigoHuesped),
    CONSTRAINT fk_hosp_hab FOREIGN KEY (CodigoHabitacion) REFERENCES tbl_Habitaciones(CodigoHabitacion)
);

CREATE TABLE tbl_Servicios (
    CodigoServicio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Tipo VARCHAR2(100) NOT NULL,
    Categoria VARCHAR2(100) NOT NULL,
    UnidadMedida VARCHAR2(20),
    PrecioUnitario NUMBER(10, 2) NOT NULL,
    TiempoPreparacion NUMBER(10,2),
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP
);

CREATE TABLE tbl_ConsumosEnc (
    CodigoConsumoEnc NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoHospedaje NUMBER NOT NULL,
    FechaConsumo TIMESTAMP NOT NULL,
    MontoTotal NUMBER(10,2),
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_cons_hosp FOREIGN KEY (CodigoHospedaje) REFERENCES tbl_Hospedajes(CodigoHospedaje)
);

CREATE TABLE tbl_ConsumosDet (
    CodigoConsumoDet NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoConsumoEnc NUMBER NOT NULL,
    CodigoServicio NUMBER NOT NULL,
    Cantidad NUMBER NOT NULL,
    PrecioUnitario NUMBER(10,2) NOT NULL,
    PrecioTotal NUMBER(10,2) NOT NULL,
    MontoTotal NUMBER(10, 2) NOT NULL,
    Observaciones VARCHAR2(255),
    Estado VARCHAR2(50),
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_det_cons_enc FOREIGN KEY (CodigoConsumoEnc) REFERENCES tbl_ConsumosEnc(CodigoConsumoEnc),
    CONSTRAINT fk_det_serv FOREIGN KEY (CodigoServicio) REFERENCES tbl_Servicios(CodigoServicio)
);

CREATE TABLE tbl_Pagos (
    CodigoPago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoHospedaje NUMBER NOT NULL,
    FechaPago TIMESTAMP NOT NULL,
    MetodoPago VARCHAR2(100) NOT NULL,
    ReferenciaPago NUMBER(19),
    Monto NUMBER(10, 2) NOT NULL,
    Propina NUMBER(10, 2),
    Impuesto NUMBER(10, 2),
    Descuento NUMBER(10, 2),
    TotalPago NUMBER(10, 2) NOT NULL,
    Estado NUMBER(1) NOT NULL,
    UsuarioCreacion VARCHAR2(50),
    FechaCreacion TIMESTAMP,
    UsuarioModificacion VARCHAR2(50),
    FechaModificacion TIMESTAMP,
    UsuarioEliminacion VARCHAR2(50),
    FechaEliminacion TIMESTAMP,
    CONSTRAINT fk_pago_hosp FOREIGN KEY (CodigoHospedaje) REFERENCES tbl_Hospedajes(CodigoHospedaje)
);
/* #endregion */