/* #region Etapa 1: Migración db_Inmobiliaria - Compatibilidad Oracle */

CREATE TABLE Tbl_Sucursal (
    CodigoSucursal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreSucursal VARCHAR2(120),
    Direccion VARCHAR2(200),
    Ciudad VARCHAR2(100),
    Departamento VARCHAR2(100),
    Telefono CHAR(15),
    Email VARCHAR2(120),
    FechaApertura DATE,
    Activa NUMBER(1),
    CapacidadEmpleados NUMBER,
    Latitud NUMBER(10,6),
    Longitud NUMBER(10,6),
    FechaRegistro TIMESTAMP
);

CREATE TABLE Tbl_Agente (
    CodigoAgente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoSucursal NUMBER,
    Nombres VARCHAR2(120),
    Apellidos VARCHAR2(120),
    DPI CHAR(13),
    Telefono CHAR(15),
    Email VARCHAR2(120),
    FechaContratacion DATE,
    Salario NUMBER(12,2),
    ComisionPorcentaje NUMBER(5,2),
    Activo NUMBER(1),
    FechaRegistro TIMESTAMP,
    CONSTRAINT fk_agente_suc FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursal(CodigoSucursal)
);

CREATE TABLE Tbl_Cliente (
    CodigoCliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombres VARCHAR2(120),
    Apellidos VARCHAR2(120),
    DPI CHAR(13),
    Nit CHAR(12),
    Telefono CHAR(15),
    Email VARCHAR2(120),
    Direccion VARCHAR2(200),
    Ciudad VARCHAR2(100),
    FechaNacimiento DATE,
    FechaRegistro TIMESTAMP,
    Activo NUMBER(1)
);

CREATE TABLE Tbl_TipoPropiedad (
    CodigoTipoPropiedad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NombreTipo VARCHAR2(100),
    Descripcion VARCHAR2(200),
    RequiereMantenimiento NUMBER(1),
    UsoPrincipal VARCHAR2(100),
    AreaPromedio NUMBER(12,2),
    PermiteMascotas NUMBER(1),
    Activo NUMBER(1),
    FechaRegistro TIMESTAMP,
    UsuarioRegistro VARCHAR2(50)
);

CREATE TABLE Tbl_Propiedad (
    CodigoPropiedad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoTipoPropiedad NUMBER,
    CodigoSucursal NUMBER,
    CodigoAgente NUMBER,
    NombrePropiedad VARCHAR2(150),
    Direccion VARCHAR2(200),
    Ciudad VARCHAR2(100),
    Departamento VARCHAR2(100),
    AreaTerreno NUMBER(12,2),
    AreaConstruccion NUMBER(12,2),
    CantidadHabitaciones NUMBER,
    CantidadBanos NUMBER,
    PrecioVenta NUMBER(14,2),
    PrecioRenta NUMBER(14,2),
    Disponible NUMBER(1),
    FechaRegistro TIMESTAMP,
    CONSTRAINT fk_prop_tipo FOREIGN KEY (CodigoTipoPropiedad) REFERENCES Tbl_TipoPropiedad(CodigoTipoPropiedad),
    CONSTRAINT fk_prop_suc FOREIGN KEY (CodigoSucursal) REFERENCES Tbl_Sucursal(CodigoSucursal),
    CONSTRAINT fk_prop_agente FOREIGN KEY (CodigoAgente) REFERENCES Tbl_Agente(CodigoAgente)
);

CREATE TABLE Tbl_Propietario (
    CodigoPropietario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombres VARCHAR2(120),
    Apellidos VARCHAR2(120),
    DPI CHAR(13),
    Nit CHAR(12),
    Telefono CHAR(15),
    Email VARCHAR2(120),
    Direccion VARCHAR2(200),
    Ciudad VARCHAR2(100),
    FechaRegistro TIMESTAMP,
    Activo NUMBER(1),
    Observaciones VARCHAR2(200)
);

CREATE TABLE Tbl_PropiedadPropietario (
    CodigoPropiedadPropietario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoPropiedad NUMBER,
    CodigoPropietario NUMBER,
    PorcentajePropiedad NUMBER(5,2),
    FechaInicio DATE,
    FechaFin DATE,
    Activo NUMBER(1),
    FechaRegistro TIMESTAMP,
    UsuarioRegistro VARCHAR2(50),
    Observaciones VARCHAR2(200),
    CONSTRAINT fk_pp_prop FOREIGN KEY (CodigoPropiedad) REFERENCES Tbl_Propiedad(CodigoPropiedad),
    CONSTRAINT fk_pp_propietario FOREIGN KEY (CodigoPropietario) REFERENCES Tbl_Propietario(CodigoPropietario)
);

CREATE TABLE Tbl_Contrato (
    CodigoContrato NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoPropiedad NUMBER,
    CodigoCliente NUMBER,
    CodigoAgente NUMBER,
    TipoContrato CHAR(1),
    FechaInicio DATE,
    FechaFin DATE,
    PrecioAcordado NUMBER(14,2),
    Deposito NUMBER(14,2),
    Estado CHAR(1),
    FechaFirma TIMESTAMP,
    Observaciones VARCHAR2(300),
    CONSTRAINT fk_cont_prop FOREIGN KEY (CodigoPropiedad) REFERENCES Tbl_Propiedad(CodigoPropiedad),
    CONSTRAINT fk_cont_cli FOREIGN KEY (CodigoCliente) REFERENCES Tbl_Cliente(CodigoCliente),
    CONSTRAINT fk_cont_agente FOREIGN KEY (CodigoAgente) REFERENCES Tbl_Agente(CodigoAgente)
);

CREATE TABLE Tbl_PagoContrato (
    CodigoPagoContrato NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoContrato NUMBER,
    FechaPago TIMESTAMP,
    MontoPago NUMBER(14,2),
    MetodoPago VARCHAR2(50),
    NumeroRecibo VARCHAR2(50),
    Banco VARCHAR2(100),
    Estado CHAR(1),
    FechaRegistro TIMESTAMP,
    UsuarioRegistro VARCHAR2(50),
    Observaciones VARCHAR2(200),
    CONSTRAINT fk_pago_cont FOREIGN KEY (CodigoContrato) REFERENCES Tbl_Contrato(CodigoContrato)
);

CREATE TABLE Tbl_VisitaPropiedad (
    CodigoVisita NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CodigoPropiedad NUMBER,
    CodigoCliente NUMBER,
    CodigoAgente NUMBER,
    FechaVisita TIMESTAMP,
    InteresCliente NUMBER(1),
    CalificacionPropiedad NUMBER,
    Comentarios VARCHAR2(300),
    Estado CHAR(1),
    FechaRegistro TIMESTAMP,
    UsuarioRegistro VARCHAR2(50),
    CONSTRAINT fk_visita_prop FOREIGN KEY (CodigoPropiedad) REFERENCES Tbl_Propiedad(CodigoPropiedad),
    CONSTRAINT fk_visita_cli FOREIGN KEY (CodigoCliente) REFERENCES Tbl_Cliente(CodigoCliente),
    CONSTRAINT fk_visita_agente FOREIGN KEY (CodigoAgente) REFERENCES Tbl_Agente(CodigoAgente)
);
/* #endregion */